### ISSUE TITLE
[CE] Check agent script is created

### ISSUE THREAD

**Issue by jananga99** [FYP-Jalien/test-suite#14]
When the setup strats running (after starting optimiser), CE will create a script which will be used to start job agents. This can be found in,
![image](https://github.com/FYP-Jalien/test-suite/assets/85403622/4f395ea8-fb0f-46f1-a0cd-bf5437850f1e)
I

- Ensure this file is created (last number may differ, so check whether a file exists hose file name has agenet.startup.[0-9][0-9] format
- Check file contains JALIEN_TOKEN_CERT
- Check file contains JALIEN_TOKEN_Key
- Check below two lines exist at the end
![image](https://github.com/FYP-Jalien/test-suite/assets/85403622/3a5b7cb5-9b0a-4c96-a585-76ba637bfdd5)
- If requires, feel free to check other content as well

**Comment by Malith-19** [comment]
When we check inside the files, do we need to check all or the latest one?
