### ISSUE TITLE
[CE] Ensure Condor is working

### ISSUE THREAD

**Issue by jananga99** [FYP-Jalien/test-suite#8]
Ensure condor_q and condor_status has outputs like this

![image](https://github.com/FYP-Jalien/test-suite/assets/85403622/e8cc04d1-6a6f-4bdc-aaa8-481121098f64)

If there is something wrong with condor_q, output would be like this
![image](https://github.com/FYP-Jalien/test-suite/assets/85403622/13c4025d-be24-42c5-9c5b-33bdebae50ce)
Error: 

Extra Info: You probably saw this error because the condor_schedd is not 
running on the machine you are trying to query. If the condor_schedd is not 
running, the Condor system will not be able to find an address and port to 
connect to and satisfy this request. Please make sure the Condor daemons are 
running and try again.
 
Extra Info: If the condor_schedd is running on the machine you are trying to 
query and you still see the error, the most likely cause is that you have 
setup a personal Condor, you have not defined SCHEDD_NAME in your 
condor_config file, and something is wrong with your SCHEDD_ADDRESS_FILE 
setting. You must define either or both of those settings in your config 
file, or you must use the -name option to condor_q. Please see the Condor 
manual for details on SCHEDD_NAME and SCHEDD_ADDRESS_FILE.

If there is something wrong with condor_status, output would be like this
![image](https://github.com/FYP-Jalien/test-suite/assets/85403622/729e1f5d-6638-42a4-899b-40e3e7bc2690)
Error: can't find collector

**Comment by Malith-19** [comment]
Any idea about how can we identify if the condor is running properly? 

```
-- Schedd: localhost.localdomain : <172.18.0.5:40373> @ 01/16/24 18:18:01
OWNER BATCH_NAME      SUBMITTED   DONE   RUN    IDLE   HOLD  TOTAL JOB_IDS

Total for query: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
Total for all users: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended
```

This is the response for the condor_q in CE. So we can validate using the first line right?

**Comment by jananga99** [comment]
> Any idea about how can we identify if the condor is running properly?
> 
> ```
> -- Schedd: localhost.localdomain : <172.18.0.5:40373> @ 01/16/24 18:18:01
> OWNER BATCH_NAME      SUBMITTED   DONE   RUN    IDLE   HOLD  TOTAL JOB_IDS
> 
> Total for query: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
> Total for all users: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended
> ```
> 
> This is the response for the condor_q in CE. So we can validate using the first line right?

After the setup starts running (probably after starting optimiser), CE should create job agents and add them to the condor queue. So, Total for all users: jobs value should be increased. Confirm that job value becomes greater than 0, and if possible it is increasing after some time.

**Comment by jananga99** [comment]
After submitting a job and after sometime, For the condor_status check whther there are slot values in Name column. Also, total is greater than 0.

**Comment by jananga99** [comment]
For this another check is needed to be done. Check the content of the below htcondor_starter.log file to check, whether condor_master entered running state
![image](https://github.com/FYP-Jalien/test-suite/assets/85403622/c5918931-c946-4607-a95c-db44e6c976e6)
